### ISSUE TITLE
Icon reverted back to default

### ISSUE THREAD

**Issue by jchrom** [cybre/megasync-elementary#1]
The monochrome icon reverted back to default red. It happened a few days ago when an update also took place. I think the version of sni-qt you use is patched somehow, possibly the update replaced your patch?

Also, what info should I provide for further diagnosis?

**Comment by cybre** [comment]
Please clone the repo again and run the installer.
I've updated the sni-qt patch to look for icons in `~/.local/share/sni-qt/icons/appName/` instead of `~/.local/share/sni-qt/icons/`.

**Comment by jchrom** [comment]
Solved, icons for all statuses work as expected. However, the slingshot icon is now missing.

**Comment by cybre** [comment]
Send me the output of `ls -l /usr/share/applications/megasync.desktop` and `cat /usr/share/applications/megasync.desktop`

**Comment by jchrom** [comment]
Actually, I take it back. I fiddled with the .desktop entry, so it was my fault. Backup version of it works just fine, so this is solved. Thanks for the lightning speed ;-)
