### ISSUE TITLE
Elementary OS Loki

### ISSUE THREAD

**Issue by andersondantas94** [cybre/megasync-elementary#2]
Need new adaptations Elementary Loki .

Now the icons are darkened by default when a light background is applied.

![captura de tela de 2016-09-12 10 14 24](https://cloud.githubusercontent.com/assets/22149209/18437094/bc298c1a-78d1-11e6-9d7c-32af36408c2e.png)

**Comment by cybre** [comment]
I'm sorry, this project has been discontinued since I've moved on from elementary. You can edit the icons to make them darker and re-run the script.
